### PR TITLE
random_bytes(0) should [perhaps do something other than return an empty string]

### PR DESCRIPTION
**Pull request by azet**
If people want to use this gem and have safe functionality, this should really not return an empty string (PHP anyone?). I'm aware this breaks SecureRandom compat. but I think it's OK to do so if someone uses this gem.

### CODE REVIEW

**Comment by tarcieri** [comment]
My preferred behavior would be to raise ArgumentError. There are already guards in place to check for < 0, they could be changed to <= 0

**Comment by azet** [comment]
I'd prefer it as well but I'm not sure how people use SecureRandom in it's current form in general.

**Comment by soatok** [comment]
I vote for ArgumentError, for reasons outlined in https://wiki.php.net/rfc/random-function-exceptions

**Comment by tarcieri** [comment]
I would be :thumbsup: for `ArgumentError`

**Comment by azet** [comment]
@tarcieri now raises ArgumentError.

**Pull request merged**
